### ISSUE TITLE
[FEAT] 엔티티 구성

### ISSUE THREAD

**Issue by Kwonhyunjun** [Kwonhyunjun/msa-project#3]
## 📎 Description 
> 엔티티 구성

## ✅ Todo
- [X] 상품 엔티티 구성 
- [X] 주문 엔티티 구성 
- [X] 주문매핑상품 엔티티 구성 (https://github.com/Kwonhyunjun/msa-project/issues/5 함께 반영)
