### ISSUE TITLE
[SETTING] 환경분리

### ISSUE THREAD

**Issue by Kwonhyunjun** [Kwonhyunjun/msa-project#9]
## 📎 Description 
> 로컬과 운영 DB 환경 분리

## ✅ Todo
- [X] Order 서비스 환경분리
- [X] Product 서비스 환경분리
- [X] Auth 서비스 환경분리
